services:
  ubuntu:
    build:
      context: ./
      dockerfile: ./build/wails-cross-compile/ubuntu2404/Dockerfile
    volumes:
      - './:/app'
  windows:
    build:
      context: ./
      dockerfile: ./build/wails-cross-compile/Dockerfile
    volumes:
      - './:/app'
