// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Generate'](arg1, arg2, arg3, arg4);
}

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetPwd() {
  return window['go']['main']['App']['GetPwd']();
}

export function GetSeparator() {
  return window['go']['main']['App']['GetSeparator']();
}
