// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Generate(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>):Promise<string>;

export function GetDirectoryTree(arg1:string):Promise<main.DirectoryTreeResponse>;

export function GetPwd():Promise<string>;

export function GetSeparator():Promise<string>;
